CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS orderdb;
CREATE DATABASE IF NOT EXISTS paymentdb;
CREATE DATABASE IF NOT EXISTS trackingdb;
CREATE DATABASE IF NOT EXISTS gudangdb;
CREATE DATABASE IF NOT EXISTS courierdb;
CREATE DATABASE IF NOT EXISTS reportdb;